# -*- coding: utf-8 -*-
"""week5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzgd5KiG0y59fMfwktufanIalzFu0DKY
"""

# ---------------------------------------------------------
# STEP 1: Import Libraries
# ---------------------------------------------------------

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# ---------------------------------------------------------
# STEP 2: Load the data
# ---------------------------------------------------------

df = pd.read_csv("/content/age_insurance.csv")

print("Dataset:")
print(df.head())

print("\nShape of dataset:")
print(df.shape)

print("\nColumn names:")
print(df.columns)


# ===========================================================
# PART 1: BINARY LOGISTIC REGRESSION
# Feature: Age
# Target: Insurance
# 0 = No Insurance
# 1 = Yes Insurance
# ===========================================================

print("\nPART 1: BINARY LOGISTIC REGRESSION")
print("-" * 45)


# ---------------------------------------------------------
# STEP 3: Select Feature and Target
# ---------------------------------------------------------

X = df[["Age"]]
y = df["Insurance"]


# ---------------------------------------------------------
# STEP 4: Split the Dataset
# ---------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


# ---------------------------------------------------------
# STEP 5: Create and Train the Model
# ---------------------------------------------------------

binary_model = LogisticRegression()

binary_model.fit(X_train, y_train)


# ---------------------------------------------------------
# STEP 6: Make Predictions
# ---------------------------------------------------------

y_pred = binary_model.predict(X_test)


# ---------------------------------------------------------
# STEP 7: Evaluate the Model
# ---------------------------------------------------------

print("\nAccuracy:")
print(accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        target_names=["No Insurance", "Has Insurance"]
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


# ---------------------------------------------------------
# STEP 8: Predict for New Ages
# ---------------------------------------------------------

new_age = pd.DataFrame({
    "Age": [22, 45, 63]
})

predictions = binary_model.predict(new_age)

print("\nPredictions:")
print(predictions)


# Probability of Insurance = 1
probabilities = binary_model.predict_proba(new_age)[:, 1]


print("\nPrediction Details:")

for age_val, pred, prob in zip(
    new_age["Age"],
    predictions,
    probabilities
):

    print(
        f"Age {age_val}: Insurance = {pred} "
        f"(Probability of Yes = {prob:.2f})"
    )


# ---------------------------------------------------------
# STEP 9: Plot Age vs Insurance
# ---------------------------------------------------------

plt.figure(figsize=(6, 4))

# Actual data
plt.scatter(
    df["Age"],
    df["Insurance"],
    color="blue",
    label="Actual Data"
)


# Create age range
age_range = pd.DataFrame({
    "Age": range(
        int(df["Age"].min()),
        int(df["Age"].max()) + 1
    )
})


# Logistic Regression S-Curve
plt.plot(
    age_range["Age"],
    binary_model.predict_proba(age_range)[:, 1],
    color="red",
    label="Predicted Probability"
)


plt.xlabel("Age")
plt.ylabel("Insurance (0 = No, 1 = Yes)")
plt.title("Binary Logistic Regression: Age vs Insurance")

plt.legend()

plt.tight_layout()


# ---------------------------------------------------------
# STEP 10: Save and Show Plot
# ---------------------------------------------------------

plt.savefig("binary_logistic_plot.png")

plt.show()

print("\nSaved plot -> binary_logistic_plot.png")